### ISSUE TITLE
Duda commit eclipse .project

### ISSUE THREAD

**Issue by migueltmz** [seryeb/vehiculo-manoslibres#2]
Cuando hago commit añade automáticamente los ficheros cambiado pero marca .project como Unstaged.
¿Puede que el problema que indicabas con .project tenga algo que ver con eso?
¿Debería añadir el .project al commit?

**Comment by migueltmz** [comment]
Parece que no tiene que ver, he encontrado quien dice que sí y quien dice que no:
https://github.com/sisoputnfrba/foro/issues/220

**Comment by seryeb** [comment]
Me imagino que dado que yo ayer al hacer el commit antes del fetch, eliminé el .proyect, y ahora ya no está en el repositorio. Para que vuelva a estar tendrías que añadirlo (stage) y después hacer el commit en local. Por último sería el push, y lo subirías a GitHub.

Si no lo quieres subir no pasa nada, se queda como unstaged, que simplemente significa que no entra al repositorio, aunque tú lo tengas en local.
