### ISSUE TITLE
Problemas con Eclipse

### ISSUE THREAD

**Issue by migueltmz** [seryeb/vehiculo-manoslibres#3]
He tenido problemas para hacer pruebas con los archivos de este repositorio y he creado un proyecto desde cero y lo he subido a mi [repositorio](https://github.com/migueltmz/vehiculo-manoslibres).
Allí está la versión más actualizada, incluido métodos conectar y contraseña...
Si queréis podemos seguir por allí, ya me decís.
Sé que es un poco lío pero así avanzamos.

**Comment by seryeb** [comment]
Pero exactamente cuál ha sido el problema?

**Comment by migueltmz** [comment]
No podía ejecutar el proyecto porque faltaban archivos, no se decirte más. He creado un proyecto nuevo, en local, y he copiado los archivos de clases, directamente y entonces sí ejecutaba.
He tirado por ahí, con los métodos contraseña y conectar y como tenía dudas de subirlo a tu repositorio, lo he subido al mío.
¿qué opinas?

**Comment by seryeb** [comment]
Ok. No problem. Donde esté es lo de menos. Cambio el repositorio por el tuyo y ya está.

Me has dado permisos para poder hacer push?

**Comment by migueltmz** [comment]
Acabo de hacerlo.

**Comment by seryeb** [comment]
Ok. Cierro este e informo en el readme del nuevo.
